export const ROLES = {
  EMPLOYEE: "EMPLOYEE",
  LINE_MANAGER: "LINE_MANAGER",
  INVENTORY_OFFICER: "INVENTORY_OFFICER",
  PROCUREMENT_OFFICER: "PROCUREMENT_OFFICER",
  FINANCE: "FINANCE",
  HR_OFFICER: "HR_OFFICER",
  SUPER_ADMIN: "SUPER_ADMIN"
};

export const ROLE_OPTIONS = Object.values(ROLES);
